// const express = require('express')
var urllib = require('urllib');
// const path = require('path')

const data = [
"abaci"          ,           
"abak",
"abakë",
"abanoz",
"abat",
"abazhur" ,
"abdes"   ,
"abdhellë",
"abdikim",
"abe",
"abë",
"abece",
"abëcë",
"abetar",
"abetare",
"abis",
"ablativ"        , 
"abonim"         , 
"abonuar"        , 
"abrogim"        , 
"absolutizëm"    , 
"absorbim"       , 
"abstenim"       , 
"abstenonjës"    , 
"absurditet"     , 
"abuzim"         , 
"acar"           , 
"acetilen"       , 
"aciditet"       , 
"adash"       ,
"aderim"      ,
"adet"        ,
"adham"          ,  
"adhrim"      ,
"adhurim"     ,
"adhuronjës"  ,
"adhurues"    ,
"adhuruese"   ,
"adjektiv"    ,
"administratë",
"administrim" ,
"administronjës" , 
"admirim"        , 
"admironjës"     , 
"admirues"       , 
"admiruese"      , 
"adoptim"        , 
"adresë"         , 
"aerodinamikëm"  , 
"aerodrom"       , 
"aeroplan"       , 
"aeroport"       , 
"afat"           , 
"afçë"           , 
"afërsi"         , 
"afërt"          , 
"afinitet"       , 
"afishe"         , 
"afishë"         , 
"afri"           , 
"afrikan"        , 
"afrikane"       , 
"afrim"          , 
"Afrim"          , 
"Afrime"         , 
"Afrimi"         , 
"Afrimja"        , 
"afsh"           , 
"aft"            , 
"aftësi"         , 
"ag"             , 
"agjërim"        , 
"ago"            , 
"agull"          , 
"ah"             , 
"ahë"            , 
"aheng"          , 
"ahishte",
"AIDS",
"aids",
"ajazmë",
"ajdës",
"ajër",
"ajkë",
"akacie",
"akoma",
"akord",
"akrep",
"akrobat",
"akth",
"aktivist",
"aktivizëm",
"aktor",
"akuarium",
"akull"      ,
"akullore",
"akuzativ",
"alarm",
"alarmim",
"alfabet",
"alkool",
"allme",
"altoparlant",
"alumin",
"amahj",
"ame",
"amë",
"amëz",
"amti",
"amull",
"amulli",
"amvisë",
"an",
"analogji",
"anarkizëm",
"anason",
"anatomi",
"ane",
"anë",
"ânë",
"anemi",
"anëtar",
"ang",
"angari",
"angërduf",
"angërr",
"angjinare",
"anglisht",
"angurrë",
"anije",
"ankesë",
"ankth",
"anmik",
"ansujë",
"antimon",
"antonim",
"antropologji",
"apë",
"aplladhe",
"apogje",
"apokalips",
"apologji",
"apostrof",
"ar",
"arab",
"arar",
"arashkë",
"arbën",
"Arbëni",
"Arbënia",
"Arbër",
"arbër",
"Arbëreshë",
"Arbëri",
"Arbëria",
"Arbi",
"ardhi",
"ardhje",
"ardhme",
"arë",
"arënx",
"arësye",
"arëz",
"arg",
"argat",
"argëtim",
"argjend",
"argjentinas",
"argjilë",
"argjinaturë",
"argsh",
"argull",
"ari",
"aristokraci",
"aristokrat",
"arith",
"aritmetikë",
"arixhi",
"arkë",
"arkeolog",
"arkeologe",
"arkeologji",
"arkipelag",
"arkitekt",
"arkitekturë",
"arkivist",
"arkiviste",
"arkivol",
"armatë",
"armë",
"armëndreqës",
"armenishte",
"armëpunues",
"armëpushim",
"armik",
"armor",
"arne",
"arnë",
"aromë"]



function get_all_albanian_nouns(){
    return data
}

const all_albanian_nouns = get_all_albanian_nouns()

function checkIFNounsInAlbanian_nouns(str){
    for (let i = 0; i < all_albanian_nouns.length; i++) {
        if (str  ==    all_albanian_nouns[i]) {
          return true  
        } 
     
     }
     return false;
}

///I could not find a JSON file return API , if I found I would pull the data that way

urllib.request('https://en.wiktionary.org/wiki/Category:Albanian_nouns', function (err, data, res) {
            let newData = JSON.parse(data.toString())
            console.log(newData);
            response.send(playersArray)
        })

